[package]
name = "chord"
version = "0.1.0"
authors = ["Michael Mokrysz <hi@46b.it>"]

[dependencies]
csv = "1.0.0-beta.3"
serde = "1.0"
serde_derive = "1.0"
sha1 = "0.2.0"
rand = "0.3"
tarpc = "0.8.0"
tarpc-plugins = "0.1.1"
futures = "0.1"
